server:
  port: 8080
  #context-path: /nut
spring:
  http:
    encoding:
      charset: UTF-8
      force: true
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/project?useUnicode=true&characterEncoding=UTF-8&autoReconnectForPools=true&serverTimezone=Hongkong
    username: root
    password:
    name: druid
    druid:
      initialSize: 2
      minIdle: 2
      maxActive: 20
      maxWait: 60000
      timeBetweenEvictionRunsMillis: 60000
      minEvictableIdleTimeMillis: 3600000
      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: true
      testOnReturn: false
#mybatis 配置
mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
